/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Dashboard: () => import('#controllers/dashboard_controller'),
  Registrations: () => import('#controllers/registrations_controller'),
  Rules: () => import('#controllers/rules_controller'),
  Sessions: () => import('#controllers/sessions_controller'),
}
